### ISSUE TITLE
Remove Commons Lang Dependency

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agentgt/jatl#14]
```
Commons Lang is slowly becoming less favorable and we only use a few methods 
from it.


Also by removing the dependency will make JATL have an even smaller footprint.


```

Original issue reported on code.google.com by `adam.g...@evocatus.com` on 12 Apr 2012 at 12:23

**Comment by godspeedyou** [comment]
Any updates on this?

**Comment by agentgt** [comment]
The code change is trivial. The real work is cutting a new release on github. I need to update the pom so that the maven release plugin works.

Let me know when you need this by (happy to take PRs as well to help expedite).

**Comment by godspeedyou** [comment]
Would be great if this gets going asap, since we moved on to lang3.

PR as in public relationships?

**Comment by agentgt** [comment]
PR as in Pull Request :)

I'm going to go ahead and update to JDK 7. Finding either a JDK 5 or JDK 6 is becoming more difficult (I don't think even Travis has support for those JDKs anymore).

**Comment by agentgt** [comment]
It is now in (I guess actually out 😄  of) 0.2.3 . The variable interpolation was replaced with simpler alternative to the commons lang that does not support recursive lookup. It is also not nearly as tested but I don't think many use it anyway.

**Comment by godspeedyou** [comment]
Big up and thanks a lot.
